export const PREVIEW_DATA = {
    BaseText: 'Muhieddeen TV',
    logoX: '30',
    logoY: '30',
    logoSize: '175',
    logo: 'off',
    waterMark: '',
    waterMarkY: null,
    waterMarkO: 5,
    waterMarkText: 'MuhieddeenTV',
    waterMarkSize: '',
    live: 'off',
    liveX: '20',
    liveY: '20',
    liveSize: '5',
    liveStyle: '',
    banner: '',
    bannerH: '',
    bannerY: '',
    bannerText1: 'Sub Title',
    bannerText2: 'Main Title',
    bannerFont: '',
    bannerText1Font: '',
    bannerText2Font: '',
    bannerSize: 2,
    news: 'off',
    newsTitle: '',
    newsTitleText: 'كيف حال',
    newsText: '1.சென்னை: மும்பை அணிக்கு எதிரான முதல் ஐபிஎல் போட்டியில் பெங்களூர் அணி டாஸ் வென்று பவுலிங் செய்ய முடிவு செய்துள்ளது;2.சென்னை: மும்பை அணிக்கு எதிரான முதல் ஐபிஎல் போட்டியில் பெங்களூர் அணி டாஸ் வென்று பவுலிங் செய்ய முடிவு செய்துள்ளது;3.சென்னை: மும்பை அணிக்கு எதிரான முதல் ஐபிஎல் போட்டியில் பெங்களூர் அணி டாஸ் வென்று பவுலிங் செய்ய முடிவு செய்துள்ளது',
    newsSize: '',
    newsPadding: '',
    newsY: '',
    newsSpeed: '',
    newsDirection: '',
    newsMove: '',
    newsFont: 'a2',
    newsStyle: 's9',
    newsTitleBg: '',
    newsTitleColor: '',
    newsBg: '',
    newsColor: '',
    tickerTitle: '',
    tickerHeight: null,
    tickerRow: null,
    tickerSpeed: 6,
    tickerDirection: null,
    tickerDuration: '3',
    tickerTitleText: 'Prayer Times',
    tickerText: 'Fajir: 5:00 am;Zuhar: 12:30 pm;Asar: 3:50 pm;Ma\'rib: 6:30 pm;Isha: 7:50 pm;Taraweeh: 9:00 pm;',
    tickerX: '',
    tickerY: '',
    tickerPadding: '',
    tickerFont: '',
    tickerStyle: 's6',
    tickerTitleBg: '',
    tickerTitleColor: '',
    tickerBg: '',
    tickerColor: '',
    tickerTitleSize: '',
    tickerSize: '',
    clock: '',
    clockX: '',
    clockY: '',
    clockStyle: '',
    clockSize: '',
    clockFormat: ''
}